name: untitled
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

# Application version and build number
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+2
  path: ^1.9.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  lottie: ^3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3+1 # For desktop database testing

# Flutter-specific settings
flutter:
  uses-material-design: true

  assets:
    - assets/images/serene_beach_page.png # Example of your image assets
    - assets/icons/treasure.png
  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf

  # Example for adding fonts (uncomment if needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic




