name: calm_quest
description: "An app for kids to practice mindfulness techniques"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.8
  dart_sentiment: ^0.0.9
  sqflite: ^2.3.3+2
  http: ^1.2.1
  path: ^1.9.0
  meta: ^1.7.0
  audioplayers: ^6.1.0
  fl_chart: ^0.69.2
  shared_preferences: ^2.3.3
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.0.0
  timezone: any
  collection: any
  gif: ^2.3.0
  intl: any
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3+1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/activity_one/
    - assets/images/
    - assets/icons/
    - assets/gamify/
    - assets/secrets.txt
    - assets/images/mistymount.png
    - assets/images/beach.png
    - assets/images/tranforest.png
    - assets/animations/twinkle_stars.json
    - assets/sounds/misty_mountain.mp3
    - assets/sounds/serene_beach.mp3
    - assets/sounds/tranquil_forest.mp3
    - assets/animations/ripple_under_nav.json
    - assets/images/serene_beach_background.png

  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
